permalink: /:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: true
markdown: redcarpet
redcarpet:
  extensions:
    - underline
    - superscript
    - strikethrough 
    - disable_indented_code_blocks
    - tables
    - hard_wrap
paginate: 5
title : "Fooleap's Blog"
tagline: fooleap, Linux, Arch Linux, 慢跑, 徒步, 骑行
author :
  name : Fooleap
  email : fooleap@gmail.com
  github : fooleap
  twitter : fooleap
  feedburner : feedname
production_url : http://blog.fooleap.org

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  comments :
    provider : disqus
    disqus :
      short_name : fooleap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light
  analytics :
    provider : google
    google :
        tracking_id : 'UA-16717905-7'
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
  sharing :
    provider : false
